project:
  type: website
  output-dir: _site

website:
  title: "Claude Code Presentation"
  description: "The Developer Productivity Multiplier"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true